Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 625, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/dist-packages/django/core/servers/basehttp.py", line 140, in handle
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 625, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/dist-packages/django/core/servers/basehttp.py", line 140, in handle
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
Invalid HTTP_HOST header: 'acm.digested.site'. You may need to add 'acm.digested.site' to ALLOWED_HOSTS.
[10/Jun/2017 05:50:28] "GET / HTTP/1.1" 400 59546
Invalid HTTP_HOST header: 'acm.digested.site'. You may need to add 'acm.digested.site' to ALLOWED_HOSTS.
[10/Jun/2017 05:50:28] "GET /favicon.ico HTTP/1.1" 400 59627
Performing system checks...

System check identified no issues (0 silenced).
June 10, 2017 - 05:48:02
Django version 1.11.2, using settings 'shuacm.settings'
Starting development server at http://0.0.0.0:80/
Quit the server with CONTROL-C.
----------------------------------------
Exception happened during processing of request from ('111.186.113.90', 47216)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('111.186.113.90', 47218)
----------------------------------------
[10/Jun/2017 05:51:22] "GET / HTTP/1.1" 200 1220
[10/Jun/2017 05:51:22] "GET /static/enroll/acm_a.png HTTP/1.1" 200 10698
[10/Jun/2017 05:51:22] "GET /static/enroll/culture.css HTTP/1.1" 200 248
[10/Jun/2017 05:51:22] "GET /static/enroll/acm_b.png HTTP/1.1" 200 8077
[10/Jun/2017 05:51:22] "GET /static/enroll/acm_c.png HTTP/1.1" 200 7477
Not Found: /favicon.ico
[10/Jun/2017 05:51:22] "GET /favicon.ico HTTP/1.1" 404 2327
[10/Jun/2017 05:53:10] "GET / HTTP/1.1" 200 1220
[10/Jun/2017 05:53:12] "GET / HTTP/1.1" 200 1220
[10/Jun/2017 05:53:12] "GET / HTTP/1.1" 200 1220
[10/Jun/2017 05:53:12] "GET /static/enroll/culture.css HTTP/1.1" 200 248
[10/Jun/2017 05:53:12] "GET /static/enroll/acm_a.png HTTP/1.1" 200 10698
[10/Jun/2017 05:53:12] "GET /static/enroll/acm_b.png HTTP/1.1" 200 8077
[10/Jun/2017 05:53:12] "GET /static/enroll/acm_c.png HTTP/1.1" 200 7477
[10/Jun/2017 05:53:27] "GET / HTTP/1.1" 200 1220
[10/Jun/2017 05:53:27] "GET /static/enroll/acm_a.png HTTP/1.1" 200 10698
[10/Jun/2017 05:53:27] "GET /static/enroll/culture.css HTTP/1.1" 200 248
[10/Jun/2017 05:53:27] "GET /static/enroll/acm_b.png HTTP/1.1" 200 8077
[10/Jun/2017 05:53:27] "GET /static/enroll/acm_c.png HTTP/1.1" 200 7477
[10/Jun/2017 05:53:44] "GET / HTTP/1.1" 200 1220
[10/Jun/2017 05:53:44] "GET /static/enroll/culture.css HTTP/1.1" 200 248
[10/Jun/2017 05:53:44] "GET /static/enroll/acm_a.png HTTP/1.1" 200 10698
[10/Jun/2017 05:53:44] "GET /static/enroll/acm_c.png HTTP/1.1" 200 7477
[10/Jun/2017 05:53:45] "GET /static/enroll/acm_b.png HTTP/1.1" 200 8077
[10/Jun/2017 05:53:56] "GET / HTTP/1.1" 200 1220
[10/Jun/2017 05:53:56] "GET /static/enroll/culture.css HTTP/1.1" 200 248
[10/Jun/2017 05:53:56] "GET /static/enroll/acm_a.png HTTP/1.1" 200 10698
[10/Jun/2017 05:53:56] "GET /static/enroll/acm_b.png HTTP/1.1" 200 8077
[10/Jun/2017 05:53:56] "GET /static/enroll/acm_c.png HTTP/1.1" 200 7477
[10/Jun/2017 05:53:57] "GET / HTTP/1.1" 200 1220
[10/Jun/2017 05:54:01] "GET / HTTP/1.1" 200 1220
[10/Jun/2017 05:54:01] "GET /static/enroll/culture.css HTTP/1.1" 200 248
[10/Jun/2017 05:54:01] "GET /static/enroll/acm_a.png HTTP/1.1" 200 10698
[10/Jun/2017 05:54:01] "GET /static/enroll/acm_c.png HTTP/1.1" 200 7477
[10/Jun/2017 05:54:01] "GET /static/enroll/acm_b.png HTTP/1.1" 200 8077
[10/Jun/2017 05:54:02] "GET / HTTP/1.1" 200 1220
[10/Jun/2017 05:54:02] "GET /static/enroll/culture.css HTTP/1.1" 200 248
[10/Jun/2017 05:54:02] "GET /static/enroll/acm_c.png HTTP/1.1" 200 7477
[10/Jun/2017 05:54:02] "GET /static/enroll/acm_a.png HTTP/1.1" 200 10698
[10/Jun/2017 05:54:02] "GET /static/enroll/acm_b.png HTTP/1.1" 200 8077
[10/Jun/2017 05:54:06] "GET / HTTP/1.1" 200 1220
[10/Jun/2017 05:54:06] "GET /static/enroll/culture.css HTTP/1.1" 200 248
[10/Jun/2017 05:54:06] "GET /static/enroll/acm_a.png HTTP/1.1" 200 10698
[10/Jun/2017 05:54:06] "GET /static/enroll/acm_b.png HTTP/1.1" 200 8077
[10/Jun/2017 05:54:06] "GET /static/enroll/acm_c.png HTTP/1.1" 200 7477
[10/Jun/2017 05:54:11] "GET / HTTP/1.1" 200 1220
Not Found: /favicon.ico
[10/Jun/2017 05:54:12] "GET /favicon.ico HTTP/1.1" 404 2327
[10/Jun/2017 05:54:11] "GET /static/enroll/culture.css HTTP/1.1" 200 248
[10/Jun/2017 05:54:11] "GET /static/enroll/acm_a.png HTTP/1.1" 200 10698
[10/Jun/2017 05:54:12] "GET /static/enroll/acm_b.png HTTP/1.1" 200 8077
[10/Jun/2017 05:54:12] "GET /static/enroll/acm_c.png HTTP/1.1" 200 7477
[10/Jun/2017 05:54:16] "GET / HTTP/1.1" 200 1220
[10/Jun/2017 05:54:28] "GET / HTTP/1.1" 200 1220
[10/Jun/2017 05:54:29] "GET /static/enroll/culture.css HTTP/1.1" 200 248
[10/Jun/2017 05:54:29] "GET /static/enroll/acm_a.png HTTP/1.1" 200 10698
[10/Jun/2017 05:54:29] "GET /static/enroll/acm_b.png HTTP/1.1" 200 8077
[10/Jun/2017 05:54:29] "GET /static/enroll/acm_c.png HTTP/1.1" 200 7477
Not Found: /favicon.ico
[10/Jun/2017 05:54:29] "GET /favicon.ico HTTP/1.1" 404 2327
[10/Jun/2017 05:54:29] "GET / HTTP/1.1" 200 1220
[10/Jun/2017 05:54:31] "GET / HTTP/1.1" 200 1220
[10/Jun/2017 05:54:31] "GET /static/enroll/culture.css HTTP/1.1" 200 248
[10/Jun/2017 05:54:31] "GET /static/enroll/acm_b.png HTTP/1.1" 200 8077
[10/Jun/2017 05:54:31] "GET /static/enroll/acm_c.png HTTP/1.1" 200 7477
[10/Jun/2017 05:54:31] "GET /static/enroll/acm_a.png HTTP/1.1" 200 10698
[10/Jun/2017 05:54:31] "GET / HTTP/1.1" 200 1220
[10/Jun/2017 05:54:31] "GET / HTTP/1.1" 200 1220
Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 625, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/dist-packages/django/core/servers/basehttp.py", line 140, in handle
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
[10/Jun/2017 05:54:31] "GET / HTTP/1.1" 200 1220
[10/Jun/2017 05:54:31] "GET /static/enroll/culture.css HTTP/1.1" 200 248
[10/Jun/2017 05:54:31] "GET /static/enroll/acm_a.png HTTP/1.1" 200 10698
[10/Jun/2017 05:54:31] "GET /static/enroll/acm_b.png HTTP/1.1" 200 8077
[10/Jun/2017 05:54:31] "GET /static/enroll/acm_c.png HTTP/1.1" 200 7477
[10/Jun/2017 05:54:31] "GET /static/enroll/culture.css HTTP/1.1" 200 248
[10/Jun/2017 05:54:31] "GET /static/enroll/acm_a.png HTTP/1.1" 200 10698
[10/Jun/2017 05:54:31] "GET /static/enroll/acm_b.png HTTP/1.1" 200 8077
[10/Jun/2017 05:54:31] "GET /static/enroll/acm_c.png HTTP/1.1" 200 7477
Not Found: /favicon.ico
[10/Jun/2017 05:54:31] "GET /favicon.ico HTTP/1.1" 404 2327
Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 625, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/dist-packages/django/core/servers/basehttp.py", line 140, in handle
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 625, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/dist-packages/django/core/servers/basehttp.py", line 140, in handle
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 625, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/dist-packages/django/core/servers/basehttp.py", line 140, in handle
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
[10/Jun/2017 05:54:36] "GET / HTTP/1.1" 200 1220
[10/Jun/2017 05:54:36] "GET /static/enroll/culture.css HTTP/1.1" 200 248
[10/Jun/2017 05:54:36] "GET /static/enroll/acm_a.png HTTP/1.1" 200 10698
[10/Jun/2017 05:54:36] "GET /static/enroll/acm_b.png HTTP/1.1" 200 8077
[10/Jun/2017 05:54:36] "GET /static/enroll/acm_c.png HTTP/1.1" 200 7477
Not Found: /favicon.ico
[10/Jun/2017 05:54:36] "GET /favicon.ico HTTP/1.1" 404 2327
Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 625, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/dist-packages/django/core/servers/basehttp.py", line 140, in handle
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
[10/Jun/2017 05:54:45] "GET / HTTP/1.1" 200 1220
[10/Jun/2017 05:54:45] "GET /static/enroll/culture.css HTTP/1.1" 200 248
[10/Jun/2017 05:54:45] "GET /static/enroll/acm_a.png HTTP/1.1" 200 10698
[10/Jun/2017 05:54:45] "GET /static/enroll/acm_b.png HTTP/1.1" 200 8077
[10/Jun/2017 05:54:45] "GET /static/enroll/acm_c.png HTTP/1.1" 200 7477
Not Found: /favicon.ico
[10/Jun/2017 05:54:46] "GET /favicon.ico HTTP/1.1" 404 2327
[10/Jun/2017 05:54:47] "GET / HTTP/1.1" 200 1220
[10/Jun/2017 05:54:48] "GET /static/enroll/culture.css HTTP/1.1" 200 248
[10/Jun/2017 05:54:48] "GET /static/enroll/acm_a.png HTTP/1.1" 200 10698
[10/Jun/2017 05:54:48] "GET /static/enroll/acm_b.png HTTP/1.1" 200 8077
[10/Jun/2017 05:54:48] "GET /static/enroll/acm_c.png HTTP/1.1" 200 7477
[10/Jun/2017 05:54:48] "POST /accept/ HTTP/1.1" 200 9
[10/Jun/2017 05:54:50] "GET / HTTP/1.1" 200 1220
[10/Jun/2017 05:54:50] "GET /static/enroll/culture.css HTTP/1.1" 200 248
[10/Jun/2017 05:54:50] "GET /static/enroll/acm_a.png HTTP/1.1" 200 10698
[10/Jun/2017 05:54:51] "GET / HTTP/1.1" 200 1220
[10/Jun/2017 05:54:51] "GET /static/enroll/culture.css HTTP/1.1" 200 248
[10/Jun/2017 05:54:51] "GET /static/enroll/acm_a.png HTTP/1.1" 200 10698
[10/Jun/2017 05:54:51] "GET /static/enroll/acm_b.png HTTP/1.1" 200 8077
[10/Jun/2017 05:54:51] "GET /static/enroll/acm_c.png HTTP/1.1" 200 7477
[10/Jun/2017 05:54:53] "GET /static/enroll/acm_b.png HTTP/1.1" 200 8077
[10/Jun/2017 05:54:53] "GET /static/enroll/acm_c.png HTTP/1.1" 200 7477
Not Found: /favicon.ico
[10/Jun/2017 05:54:53] "GET /favicon.ico HTTP/1.1" 404 2327
[10/Jun/2017 05:54:55] "GET / HTTP/1.1" 200 1220
[10/Jun/2017 05:55:01] "GET / HTTP/1.1" 200 1220
[10/Jun/2017 05:55:02] "GET /static/enroll/acm_b.png HTTP/1.1" 200 8077
[10/Jun/2017 05:55:02] "GET / HTTP/1.1" 200 1220
[10/Jun/2017 05:55:02] "GET /static/enroll/culture.css HTTP/1.1" 200 248
[10/Jun/2017 05:55:02] "GET /static/enroll/acm_a.png HTTP/1.1" 200 10698
[10/Jun/2017 05:55:02] "GET /static/enroll/acm_b.png HTTP/1.1" 200 8077
[10/Jun/2017 05:55:02] "GET /static/enroll/acm_c.png HTTP/1.1" 200 7477
[10/Jun/2017 05:55:02] "GET /static/enroll/culture.css HTTP/1.1" 200 248
[10/Jun/2017 05:55:02] "GET /static/enroll/acm_a.png HTTP/1.1" 200 10698
[10/Jun/2017 05:55:02] "GET /static/enroll/acm_c.png HTTP/1.1" 200 7477
[10/Jun/2017 05:55:02] "GET / HTTP/1.1" 200 1220
[10/Jun/2017 05:55:02] "GET /static/enroll/culture.css HTTP/1.1" 200 248
[10/Jun/2017 05:55:02] "GET /static/enroll/acm_a.png HTTP/1.1" 200 10698
[10/Jun/2017 05:55:02] "GET /static/enroll/acm_b.png HTTP/1.1" 200 8077
[10/Jun/2017 05:55:02] "GET /static/enroll/acm_c.png HTTP/1.1" 200 7477
Not Found: /favicon.ico
[10/Jun/2017 05:55:03] "GET /favicon.ico HTTP/1.1" 404 2327
[10/Jun/2017 05:55:07] "GET / HTTP/1.1" 200 1220
[10/Jun/2017 05:55:07] "GET /static/enroll/culture.css HTTP/1.1" 200 248
[10/Jun/2017 05:55:07] "GET /static/enroll/acm_a.png HTTP/1.1" 200 10698
[10/Jun/2017 05:55:07] "GET /static/enroll/acm_c.png HTTP/1.1" 200 7477
[10/Jun/2017 05:55:07] "GET /static/enroll/acm_b.png HTTP/1.1" 200 8077
[10/Jun/2017 05:55:09] "GET /output HTTP/1.1" 301 0
[10/Jun/2017 05:55:09] "GET /output/ HTTP/1.1" 200 441
[10/Jun/2017 05:55:10] "GET / HTTP/1.1" 200 1220
[10/Jun/2017 05:55:10] "GET /static/enroll/acm_a.png HTTP/1.1" 200 10698
[10/Jun/2017 05:55:10] "GET /static/enroll/culture.css HTTP/1.1" 200 248
[10/Jun/2017 05:55:10] "GET /static/enroll/acm_b.png HTTP/1.1" 200 8077
[10/Jun/2017 05:55:10] "GET /static/enroll/acm_c.png HTTP/1.1" 200 7477
[10/Jun/2017 05:55:12] "POST /accept/ HTTP/1.1" 200 9
[10/Jun/2017 05:55:13] "GET / HTTP/1.1" 200 1220
[10/Jun/2017 05:55:13] "GET /static/enroll/culture.css HTTP/1.1" 200 248
[10/Jun/2017 05:55:13] "GET /static/enroll/acm_a.png HTTP/1.1" 200 10698
[10/Jun/2017 05:55:13] "GET /static/enroll/acm_b.png HTTP/1.1" 200 8077
[10/Jun/2017 05:55:13] "GET /static/enroll/acm_c.png HTTP/1.1" 200 7477
[10/Jun/2017 05:55:14] "GET / HTTP/1.1" 200 1220
[10/Jun/2017 05:55:14] "GET /static/enroll/culture.css HTTP/1.1" 200 248
[10/Jun/2017 05:55:14] "GET /static/enroll/acm_a.png HTTP/1.1" 200 10698
[10/Jun/2017 05:55:15] "GET / HTTP/1.1" 200 1220
[10/Jun/2017 05:55:15] "GET /static/enroll/acm_b.png HTTP/1.1" 200 8077
[10/Jun/2017 05:55:15] "GET /static/enroll/acm_c.png HTTP/1.1" 200 7477
Not Found: /favicon.ico
[10/Jun/2017 05:55:16] "GET /favicon.ico HTTP/1.1" 404 2327
[10/Jun/2017 05:55:16] "GET / HTTP/1.1" 200 1220
[10/Jun/2017 05:55:16] "GET /static/enroll/culture.css HTTP/1.1" 200 248
[10/Jun/2017 05:55:16] "GET /static/enroll/acm_a.png HTTP/1.1" 200 10698
[10/Jun/2017 05:55:16] "GET /static/enroll/acm_b.png HTTP/1.1" 200 8077
[10/Jun/2017 05:55:16] "GET /static/enroll/acm_c.png HTTP/1.1" 200 7477
[10/Jun/2017 05:55:20] "GET / HTTP/1.1" 200 1220
[10/Jun/2017 05:55:20] "GET /static/enroll/culture.css HTTP/1.1" 200 248
[10/Jun/2017 05:55:20] "GET /static/enroll/acm_b.png HTTP/1.1" 200 8077
[10/Jun/2017 05:55:20] "GET /static/enroll/acm_c.png HTTP/1.1" 200 7477
[10/Jun/2017 05:55:20] "GET /static/enroll/acm_a.png HTTP/1.1" 200 10698
Not Found: /favicon.ico
[10/Jun/2017 05:55:20] "GET /favicon.ico HTTP/1.1" 404 2327
[10/Jun/2017 05:55:20] "GET / HTTP/1.1" 200 1220
[10/Jun/2017 05:55:20] "GET /static/enroll/culture.css HTTP/1.1" 200 248
[10/Jun/2017 05:55:20] "GET /static/enroll/acm_a.png HTTP/1.1" 200 10698
[10/Jun/2017 05:55:20] "GET /static/enroll/acm_b.png HTTP/1.1" 200 8077
[10/Jun/2017 05:55:20] "GET /static/enroll/acm_c.png HTTP/1.1" 200 7477
Not Found: /favicon.ico
[10/Jun/2017 05:55:21] "GET /favicon.ico HTTP/1.1" 404 2327
[10/Jun/2017 05:55:22] "POST /accept/ HTTP/1.1" 200 9
[10/Jun/2017 05:55:27] "POST /accept/ HTTP/1.1" 200 9
[10/Jun/2017 05:55:32] "GET / HTTP/1.1" 200 1220
[10/Jun/2017 05:55:32] "GET /?_t_t_t=0.8685139488052984 HTTP/1.1" 200 1220
[10/Jun/2017 05:55:32] "GET /static/enroll/culture.css HTTP/1.1" 200 248
[10/Jun/2017 05:55:32] "GET /static/enroll/acm_a.png HTTP/1.1" 200 10698
[10/Jun/2017 05:55:32] "GET /static/enroll/acm_b.png HTTP/1.1" 200 8077
[10/Jun/2017 05:55:32] "GET /static/enroll/acm_c.png HTTP/1.1" 200 7477
[10/Jun/2017 05:55:33] "GET / HTTP/1.1" 200 1220
[10/Jun/2017 05:55:33] "GET /static/enroll/culture.css HTTP/1.1" 200 248
[10/Jun/2017 05:55:33] "GET /static/enroll/acm_b.png HTTP/1.1" 200 8077
[10/Jun/2017 05:55:33] "GET /static/enroll/acm_a.png HTTP/1.1" 200 10698
[10/Jun/2017 05:55:33] "GET /static/enroll/acm_c.png HTTP/1.1" 200 7477
Not Found: /favicon.ico
[10/Jun/2017 05:55:33] "GET /favicon.ico HTTP/1.1" 404 2327
[10/Jun/2017 05:55:34] "GET / HTTP/1.1" 200 1220
[10/Jun/2017 05:55:35] "GET / HTTP/1.1" 200 1220
[10/Jun/2017 05:55:35] "GET /static/enroll/culture.css HTTP/1.1" 200 248
[10/Jun/2017 05:55:35] "GET / HTTP/1.1" 200 1220
[10/Jun/2017 05:55:35] "GET / HTTP/1.1" 200 1220
[10/Jun/2017 05:55:35] "GET / HTTP/1.1" 200 1220
[10/Jun/2017 05:55:35] "GET / HTTP/1.1" 200 1220
[10/Jun/2017 05:55:39] "GET / HTTP/1.1" 200 1220
[10/Jun/2017 05:55:39] "GET /static/enroll/culture.css HTTP/1.1" 200 248
[10/Jun/2017 05:55:39] "GET /static/enroll/acm_a.png HTTP/1.1" 200 10698
[10/Jun/2017 05:55:39] "GET /static/enroll/acm_b.png HTTP/1.1" 200 8077
[10/Jun/2017 05:55:39] "GET /static/enroll/acm_c.png HTTP/1.1" 200 7477
[10/Jun/2017 05:55:42] "GET /?_t_t_t=0.8685139488052984 HTTP/1.1" 200 1220
[10/Jun/2017 05:55:42] "GET / HTTP/1.1" 200 1220
[10/Jun/2017 05:55:42] "GET /static/enroll/culture.css HTTP/1.1" 200 248
[10/Jun/2017 05:55:42] "GET /static/enroll/acm_b.png HTTP/1.1" 200 8077
[10/Jun/2017 05:55:42] "GET /static/enroll/acm_c.png HTTP/1.1" 200 7477
[10/Jun/2017 05:55:43] "GET /static/enroll/acm_a.png HTTP/1.1" 200 10698
Not Found: /favicon.ico
[10/Jun/2017 05:55:44] "GET /favicon.ico HTTP/1.1" 404 2327
[10/Jun/2017 05:55:47] "GET / HTTP/1.1" 200 1220
[10/Jun/2017 05:55:47] "GET /static/enroll/culture.css HTTP/1.1" 200 248
[10/Jun/2017 05:55:47] "GET / HTTP/1.1" 200 1220
[10/Jun/2017 05:55:47] "GET /static/enroll/culture.css HTTP/1.1" 200 248
[10/Jun/2017 05:55:50] "GET / HTTP/1.1" 200 1220
[10/Jun/2017 05:55:50] "GET /static/enroll/culture.css HTTP/1.1" 200 248
[10/Jun/2017 05:55:53] "GET / HTTP/1.1" 200 1220
[10/Jun/2017 05:55:54] "GET / HTTP/1.1" 200 1220
[10/Jun/2017 05:55:56] "GET / HTTP/1.1" 200 1220
[10/Jun/2017 05:55:56] "GET / HTTP/1.1" 200 1220
[10/Jun/2017 05:55:59] "GET / HTTP/1.1" 200 1220
[10/Jun/2017 05:56:00] "GET / HTTP/1.1" 200 1220
[10/Jun/2017 05:56:00] "GET /static/enroll/culture.css HTTP/1.1" 200 248
[10/Jun/2017 05:56:00] "GET /static/enroll/acm_a.png HTTP/1.1" 200 10698
[10/Jun/2017 05:56:00] "GET /static/enroll/acm_b.png HTTP/1.1" 200 8077
[10/Jun/2017 05:56:00] "GET /static/enroll/acm_c.png HTTP/1.1" 200 7477
[10/Jun/2017 05:56:03] "GET / HTTP/1.1" 200 1220
[10/Jun/2017 05:56:07] "POST /accept/ HTTP/1.1" 200 9
[10/Jun/2017 05:56:12] "GET / HTTP/1.1" 200 1220
[10/Jun/2017 05:56:23] "GET / HTTP/1.1" 200 1220
[10/Jun/2017 05:56:23] "GET / HTTP/1.1" 200 1220
[10/Jun/2017 05:56:23] "GET /static/enroll/culture.css HTTP/1.1" 200 248
[10/Jun/2017 05:56:23] "GET /static/enroll/culture.css HTTP/1.1" 200 248
[10/Jun/2017 05:56:23] "GET /static/enroll/acm_a.png HTTP/1.1" 200 10698
[10/Jun/2017 05:56:23] "GET /static/enroll/acm_b.png HTTP/1.1" 200 8077
[10/Jun/2017 05:56:23] "GET /static/enroll/acm_c.png HTTP/1.1" 200 7477
[10/Jun/2017 05:56:23] "GET / HTTP/1.1" 200 1220
[10/Jun/2017 05:56:23] "GET /static/enroll/acm_c.png HTTP/1.1" 200 7477
[10/Jun/2017 05:56:23] "GET /static/enroll/acm_b.png HTTP/1.1" 200 8077
[10/Jun/2017 05:56:23] "GET /static/enroll/acm_a.png HTTP/1.1" 200 10698
[10/Jun/2017 05:56:23] "GET /static/enroll/culture.css HTTP/1.1" 200 248
[10/Jun/2017 05:56:26] "GET / HTTP/1.1" 200 1220
[10/Jun/2017 05:56:28] "GET /output/ HTTP/1.1" 200 1019
[10/Jun/2017 05:56:33] "GET / HTTP/1.1" 200 1220
[10/Jun/2017 05:56:33] "GET /static/enroll/culture.css HTTP/1.1" 200 248
[10/Jun/2017 05:56:33] "GET /static/enroll/acm_a.png HTTP/1.1" 200 10698
[10/Jun/2017 05:56:33] "GET /static/enroll/acm_b.png HTTP/1.1" 200 8077
[10/Jun/2017 05:56:33] "GET /static/enroll/acm_c.png HTTP/1.1" 200 7477
Not Found: /favicon.ico
[10/Jun/2017 05:56:33] "GET /favicon.ico HTTP/1.1" 404 2327
[10/Jun/2017 05:56:51] "GET / HTTP/1.1" 200 1220
[10/Jun/2017 05:56:52] "GET /static/enroll/acm_a.png HTTP/1.1" 200 10698
[10/Jun/2017 05:56:52] "GET /static/enroll/culture.css HTTP/1.1" 200 248
[10/Jun/2017 05:56:52] "GET /static/enroll/acm_b.png HTTP/1.1" 200 8077
[10/Jun/2017 05:56:52] "GET /static/enroll/acm_c.png HTTP/1.1" 200 7477
[10/Jun/2017 05:56:53] "GET / HTTP/1.1" 200 1220
[10/Jun/2017 05:56:53] "GET /static/enroll/culture.css HTTP/1.1" 200 248
[10/Jun/2017 05:56:53] "GET /static/enroll/acm_a.png HTTP/1.1" 200 10698
[10/Jun/2017 05:56:53] "GET /static/enroll/acm_b.png HTTP/1.1" 200 8077
[10/Jun/2017 05:56:53] "GET /static/enroll/acm_c.png HTTP/1.1" 200 7477
[10/Jun/2017 05:57:10] "GET /output/ HTTP/1.1" 200 1019
[10/Jun/2017 05:57:10] "GET / HTTP/1.1" 200 1220
[10/Jun/2017 05:57:11] "GET /static/enroll/culture.css HTTP/1.1" 200 248
[10/Jun/2017 05:57:11] "GET /static/enroll/acm_a.png HTTP/1.1" 200 10698
[10/Jun/2017 05:57:11] "GET /static/enroll/acm_b.png HTTP/1.1" 200 8077
[10/Jun/2017 05:57:11] "GET /static/enroll/acm_c.png HTTP/1.1" 200 7477
[10/Jun/2017 05:57:15] "GET / HTTP/1.1" 200 1220
[10/Jun/2017 05:57:15] "GET /static/enroll/culture.css HTTP/1.1" 200 248
[10/Jun/2017 05:57:15] "GET /static/enroll/acm_a.png HTTP/1.1" 200 10698
[10/Jun/2017 05:57:15] "GET /static/enroll/acm_b.png HTTP/1.1" 200 8077
[10/Jun/2017 05:57:15] "GET /static/enroll/acm_c.png HTTP/1.1" 200 7477
[10/Jun/2017 05:57:15] "GET / HTTP/1.1" 200 1220
Not Found: /favicon.ico
[10/Jun/2017 05:57:16] "GET /favicon.ico HTTP/1.1" 404 2327
[10/Jun/2017 05:57:17] "GET / HTTP/1.1" 200 1220
[10/Jun/2017 05:57:17] "GET /static/enroll/culture.css HTTP/1.1" 200 248
[10/Jun/2017 05:57:17] "GET /static/enroll/acm_a.png HTTP/1.1" 200 10698
[10/Jun/2017 05:57:17] "GET /static/enroll/acm_b.png HTTP/1.1" 200 8077
[10/Jun/2017 05:57:17] "GET /static/enroll/acm_c.png HTTP/1.1" 200 7477
[10/Jun/2017 05:57:18] "GET / HTTP/1.1" 200 1220
[10/Jun/2017 05:57:18] "GET /static/enroll/culture.css HTTP/1.1" 200 248
[10/Jun/2017 05:57:18] "GET /static/enroll/acm_a.png HTTP/1.1" 200 10698
[10/Jun/2017 05:57:18] "GET /static/enroll/acm_b.png HTTP/1.1" 200 8077
[10/Jun/2017 05:57:18] "GET /static/enroll/acm_c.png HTTP/1.1" 200 7477
[10/Jun/2017 05:57:18] "GET /admin/ HTTP/1.1" 302 0
[10/Jun/2017 05:57:18] "GET /admin/login/?next=/admin/ HTTP/1.1" 200 1650
[10/Jun/2017 05:57:18] "GET /static/admin/css/base.css HTTP/1.1" 200 16066
[10/Jun/2017 05:57:18] "GET /static/admin/css/login.css HTTP/1.1" 200 1203
[10/Jun/2017 05:57:18] "GET /static/admin/css/fonts.css HTTP/1.1" 200 423
[10/Jun/2017 05:57:18] "GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 200 81348
[10/Jun/2017 05:57:18] "GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 200 80304
[10/Jun/2017 05:57:19] "GET / HTTP/1.1" 200 1220
[10/Jun/2017 05:57:20] "GET /static/enroll/culture.css HTTP/1.1" 200 248
[10/Jun/2017 05:57:20] "GET /static/enroll/acm_a.png HTTP/1.1" 200 10698
[10/Jun/2017 05:57:20] "GET /static/enroll/acm_b.png HTTP/1.1" 200 8077
[10/Jun/2017 05:57:20] "GET /static/enroll/acm_c.png HTTP/1.1" 200 7477
[10/Jun/2017 05:57:28] "POST /admin/login/?next=/admin/ HTTP/1.1" 302 0
[10/Jun/2017 05:57:28] "GET /admin/ HTTP/1.1" 200 4248
[10/Jun/2017 05:57:28] "GET /static/admin/css/dashboard.css HTTP/1.1" 200 412
[10/Jun/2017 05:57:28] "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 200 331
[10/Jun/2017 05:57:28] "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 200 380
[10/Jun/2017 05:57:28] "GET /static/admin/img/icon-deletelink.svg HTTP/1.1" 200 392
[10/Jun/2017 05:57:28] "GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 200 82564
[10/Jun/2017 05:57:33] "GET / HTTP/1.1" 200 1220
[10/Jun/2017 05:57:33] "GET /static/enroll/culture.css HTTP/1.1" 200 248
[10/Jun/2017 05:57:33] "GET /static/enroll/acm_a.png HTTP/1.1" 200 10698
[10/Jun/2017 05:57:33] "GET /static/enroll/acm_b.png HTTP/1.1" 200 8077
[10/Jun/2017 05:57:33] "GET /static/enroll/acm_c.png HTTP/1.1" 200 7477
Not Found: /favicon.ico
[10/Jun/2017 05:57:33] "GET /favicon.ico HTTP/1.1" 404 2327
[10/Jun/2017 05:57:33] "GET /admin/enroll/acmer/ HTTP/1.1" 200 5333
[10/Jun/2017 05:57:33] "GET /static/admin/css/changelists.css HTTP/1.1" 200 6170
[10/Jun/2017 05:57:33] "GET /static/admin/js/core.js HTTP/1.1" 200 7976
[10/Jun/2017 05:57:33] "GET /admin/jsi18n/ HTTP/1.1" 200 3189
[10/Jun/2017 05:57:33] "GET /static/admin/js/jquery.init.js HTTP/1.1" 200 363
[10/Jun/2017 05:57:33] "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 200 6591
[10/Jun/2017 05:57:33] "GET /static/admin/js/actions.js HTTP/1.1" 200 6501
[10/Jun/2017 05:57:33] "GET /static/admin/js/urlify.js HTTP/1.1" 200 8186
[10/Jun/2017 05:57:33] "GET /static/admin/js/prepopulate.js HTTP/1.1" 200 1538
[10/Jun/2017 05:57:35] "POST /accept/ HTTP/1.1" 200 33
[10/Jun/2017 05:57:35] "GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 200 128820
[10/Jun/2017 05:57:36] "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 200 258648
[10/Jun/2017 05:57:36] "GET /static/admin/img/tooltag-add.svg HTTP/1.1" 200 331
[10/Jun/2017 05:57:38] "GET / HTTP/1.1" 200 1220
[10/Jun/2017 05:57:38] "GET /static/enroll/culture.css HTTP/1.1" 200 248
[10/Jun/2017 05:57:38] "GET /static/enroll/acm_a.png HTTP/1.1" 200 10698
[10/Jun/2017 05:57:39] "GET /static/enroll/acm_b.png HTTP/1.1" 200 8077
[10/Jun/2017 05:57:39] "GET /static/enroll/acm_c.png HTTP/1.1" 200 7477
[10/Jun/2017 05:57:40] "GET / HTTP/1.1" 200 1220
[10/Jun/2017 05:57:44] "GET / HTTP/1.1" 200 1220
[10/Jun/2017 05:57:44] "GET /static/enroll/culture.css HTTP/1.1" 200 248
[10/Jun/2017 05:57:44] "GET /static/enroll/acm_a.png HTTP/1.1" 200 10698
[10/Jun/2017 05:57:44] "GET /static/enroll/acm_b.png HTTP/1.1" 200 8077
[10/Jun/2017 05:57:44] "GET /static/enroll/acm_c.png HTTP/1.1" 200 7477
Not Found: /favicon.ico
[10/Jun/2017 05:57:44] "GET /favicon.ico HTTP/1.1" 404 2327
[10/Jun/2017 05:57:47] "GET /admin/ HTTP/1.1" 200 4248
[10/Jun/2017 05:57:49] "GET /admin/login/?next=/admin/ HTTP/1.1" 302 0
[10/Jun/2017 05:57:49] "GET /admin/ HTTP/1.1" 200 4248
[10/Jun/2017 05:57:52] "GET / HTTP/1.1" 200 1220
[10/Jun/2017 05:57:52] "GET /static/enroll/acm_c.png HTTP/1.1" 200 7477
[10/Jun/2017 05:57:52] "GET /static/enroll/acm_a.png HTTP/1.1" 200 10698
[10/Jun/2017 05:57:52] "GET /static/enroll/culture.css HTTP/1.1" 200 248
[10/Jun/2017 05:57:52] "GET /static/enroll/acm_b.png HTTP/1.1" 200 8077
[10/Jun/2017 05:57:54] "GET /output/ HTTP/1.1" 200 1019
[10/Jun/2017 05:57:56] "POST /accept/ HTTP/1.1" 200 33
Not Found: /favicon.ico
[10/Jun/2017 05:57:56] "GET /favicon.ico HTTP/1.1" 404 2327
[10/Jun/2017 05:58:04] "GET / HTTP/1.1" 200 1220
[10/Jun/2017 05:58:05] "GET /static/enroll/culture.css HTTP/1.1" 200 248
[10/Jun/2017 05:58:05] "GET /static/enroll/acm_a.png HTTP/1.1" 200 10698
[10/Jun/2017 05:58:05] "GET /static/enroll/acm_b.png HTTP/1.1" 200 8077
[10/Jun/2017 05:58:05] "GET /static/enroll/acm_c.png HTTP/1.1" 200 7477
[10/Jun/2017 05:58:05] "GET / HTTP/1.1" 200 1220
[10/Jun/2017 05:58:05] "GET /static/enroll/culture.css HTTP/1.1" 200 248
[10/Jun/2017 05:58:05] "GET /static/enroll/acm_a.png HTTP/1.1" 200 10698
[10/Jun/2017 05:58:05] "GET /static/enroll/acm_b.png HTTP/1.1" 200 8077
[10/Jun/2017 05:58:05] "GET /static/enroll/acm_c.png HTTP/1.1" 200 7477
[10/Jun/2017 05:58:27] "GET / HTTP/1.1" 200 1220
[10/Jun/2017 05:58:27] "GET /static/enroll/culture.css HTTP/1.1" 200 248
[10/Jun/2017 05:58:27] "GET /static/enroll/acm_a.png HTTP/1.1" 200 10698
[10/Jun/2017 05:58:27] "GET /static/enroll/acm_b.png HTTP/1.1" 200 8077
[10/Jun/2017 05:58:28] "GET /static/enroll/acm_c.png HTTP/1.1" 200 7477
[10/Jun/2017 05:58:35] "GET / HTTP/1.1" 200 1220
[10/Jun/2017 05:58:35] "GET /static/enroll/acm_a.png HTTP/1.1" 200 10698
[10/Jun/2017 05:58:35] "GET /static/enroll/culture.css HTTP/1.1" 200 248
[10/Jun/2017 05:58:35] "GET /static/enroll/acm_b.png HTTP/1.1" 200 8077
[10/Jun/2017 05:58:35] "GET /static/enroll/acm_c.png HTTP/1.1" 200 7477
Not Found: /favicon.ico
[10/Jun/2017 05:58:35] "GET /favicon.ico HTTP/1.1" 404 2327
[10/Jun/2017 05:58:37] "GET / HTTP/1.1" 200 1220
[10/Jun/2017 05:58:40] "POST /accept/ HTTP/1.1" 200 9
[10/Jun/2017 05:58:40] "GET / HTTP/1.1" 200 1220
[10/Jun/2017 05:59:02] "POST /accept/ HTTP/1.1" 200 9
[10/Jun/2017 05:59:17] "POST /accept/ HTTP/1.1" 200 9
[10/Jun/2017 05:59:30] "POST /accept/ HTTP/1.1" 200 9
[10/Jun/2017 05:59:41] "GET / HTTP/1.1" 200 1220
[10/Jun/2017 06:00:01] "GET / HTTP/1.1" 200 1220
[10/Jun/2017 06:00:01] "GET /static/enroll/culture.css HTTP/1.1" 200 248
[10/Jun/2017 06:00:01] "GET /static/enroll/acm_a.png HTTP/1.1" 200 10698
[10/Jun/2017 06:00:01] "GET /static/enroll/acm_c.png HTTP/1.1" 200 7477
[10/Jun/2017 06:00:01] "GET /static/enroll/acm_b.png HTTP/1.1" 200 8077
[10/Jun/2017 06:00:02] "GET / HTTP/1.1" 200 1220
[10/Jun/2017 06:00:04] "GET /static/enroll/culture.css HTTP/1.1" 200 248
[10/Jun/2017 06:00:04] "GET /static/enroll/acm_a.png HTTP/1.1" 200 10698
[10/Jun/2017 06:00:04] "GET /static/enroll/acm_b.png HTTP/1.1" 200 8077
[10/Jun/2017 06:00:05] "GET /static/enroll/acm_c.png HTTP/1.1" 200 7477
[10/Jun/2017 06:00:09] "GET / HTTP/1.1" 200 1220
[10/Jun/2017 06:00:10] "GET / HTTP/1.1" 200 1220
[10/Jun/2017 06:00:15] "GET /static/enroll/culture.css HTTP/1.1" 200 248
[10/Jun/2017 06:00:35] "GET / HTTP/1.1" 200 1220
[10/Jun/2017 06:00:36] "GET /static/enroll/culture.css HTTP/1.1" 304 0
[10/Jun/2017 06:00:36] "GET /static/enroll/acm_a.png HTTP/1.1" 304 0
[10/Jun/2017 06:00:36] "GET /static/enroll/acm_b.png HTTP/1.1" 304 0
[10/Jun/2017 06:00:36] "GET /static/enroll/acm_c.png HTTP/1.1" 304 0
[10/Jun/2017 06:00:38] "GET / HTTP/1.1" 200 1220
[10/Jun/2017 06:00:38] "GET /static/enroll/culture.css HTTP/1.1" 200 248
[10/Jun/2017 06:00:38] "GET /static/enroll/acm_a.png HTTP/1.1" 200 10698
[10/Jun/2017 06:00:38] "GET /static/enroll/acm_b.png HTTP/1.1" 200 8077
[10/Jun/2017 06:00:38] "GET /static/enroll/acm_c.png HTTP/1.1" 200 7477
[10/Jun/2017 06:00:42] "POST /accept/ HTTP/1.1" 200 9
[10/Jun/2017 06:00:52] "GET /accept HTTP/1.1" 301 0
Internal Server Error: /accept/
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/utils/datastructures.py", line 83, in __getitem__
    list_ = super(MultiValueDict, self).__getitem__(key)
KeyError: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/shuacm_enroll/enroll/views.py", line 9, in accept
    if len(request.POST['name'])== 0 or len(request.POST['name']) > 10:
  File "/usr/local/lib/python3.5/dist-packages/django/utils/datastructures.py", line 85, in __getitem__
    raise MultiValueDictKeyError(repr(key))
django.utils.datastructures.MultiValueDictKeyError: "'name'"
[10/Jun/2017 06:00:52] "GET /accept/ HTTP/1.1" 500 69793
[10/Jun/2017 06:00:58] "POST /accept/ HTTP/1.1" 200 9
[10/Jun/2017 06:01:05] "GET / HTTP/1.1" 200 1220
[10/Jun/2017 06:01:06] "GET /static/enroll/culture.css HTTP/1.1" 200 248
[10/Jun/2017 06:01:06] "GET /static/enroll/acm_a.png HTTP/1.1" 200 10698
[10/Jun/2017 06:01:06] "GET /static/enroll/acm_b.png HTTP/1.1" 200 8077
[10/Jun/2017 06:01:06] "GET /static/enroll/acm_c.png HTTP/1.1" 200 7477
[10/Jun/2017 06:01:14] "GET / HTTP/1.1" 200 1220
[10/Jun/2017 06:01:14] "GET /static/enroll/acm_a.png HTTP/1.1" 200 10698
[10/Jun/2017 06:01:14] "GET /static/enroll/culture.css HTTP/1.1" 200 248
[10/Jun/2017 06:01:14] "GET /static/enroll/acm_b.png HTTP/1.1" 200 8077
[10/Jun/2017 06:01:14] "GET /static/enroll/acm_c.png HTTP/1.1" 200 7477
[10/Jun/2017 06:01:24] "GET / HTTP/1.1" 200 1220
[10/Jun/2017 06:01:24] "GET /static/enroll/culture.css HTTP/1.1" 200 248
[10/Jun/2017 06:01:24] "GET /static/enroll/acm_a.png HTTP/1.1" 200 10698
[10/Jun/2017 06:01:24] "GET /static/enroll/acm_b.png HTTP/1.1" 200 8077
[10/Jun/2017 06:01:24] "GET /static/enroll/acm_c.png HTTP/1.1" 200 7477
[10/Jun/2017 06:01:39] "GET / HTTP/1.1" 200 1220
[10/Jun/2017 06:01:40] "GET /static/enroll/culture.css HTTP/1.1" 304 0
[10/Jun/2017 06:01:40] "GET /static/enroll/acm_a.png HTTP/1.1" 304 0
[10/Jun/2017 06:01:40] "GET /static/enroll/acm_b.png HTTP/1.1" 304 0
[10/Jun/2017 06:01:40] "GET /static/enroll/acm_c.png HTTP/1.1" 304 0
[10/Jun/2017 06:01:44] "GET / HTTP/1.1" 200 1220
[10/Jun/2017 06:01:44] "GET /static/enroll/culture.css HTTP/1.1" 200 248
[10/Jun/2017 06:01:44] "GET /static/enroll/acm_c.png HTTP/1.1" 200 7477
[10/Jun/2017 06:01:44] "GET /static/enroll/acm_b.png HTTP/1.1" 200 8077
[10/Jun/2017 06:01:44] "GET /static/enroll/acm_a.png HTTP/1.1" 200 10698
Not Found: /favicon.ico
[10/Jun/2017 06:01:44] "GET /favicon.ico HTTP/1.1" 404 2327
[10/Jun/2017 06:01:50] "GET / HTTP/1.1" 200 1220
[10/Jun/2017 06:01:50] "GET / HTTP/1.1" 200 1220
[10/Jun/2017 06:01:50] "GET /static/enroll/culture.css HTTP/1.1" 200 248
[10/Jun/2017 06:01:50] "GET /static/enroll/acm_a.png HTTP/1.1" 200 10698
[10/Jun/2017 06:01:50] "GET /static/enroll/acm_b.png HTTP/1.1" 200 8077
[10/Jun/2017 06:01:50] "GET /static/enroll/acm_c.png HTTP/1.1" 200 7477
[10/Jun/2017 06:01:52] "GET / HTTP/1.1" 200 1220
[10/Jun/2017 06:01:53] "GET /static/enroll/culture.css HTTP/1.1" 304 0
[10/Jun/2017 06:01:53] "GET /static/enroll/acm_a.png HTTP/1.1" 304 0
[10/Jun/2017 06:01:53] "GET /static/enroll/acm_b.png HTTP/1.1" 304 0
[10/Jun/2017 06:01:53] "GET /static/enroll/acm_c.png HTTP/1.1" 304 0
[10/Jun/2017 06:01:58] "POST /accept/ HTTP/1.1" 200 9
[10/Jun/2017 06:02:05] "GET /static/enroll/culture.css HTTP/1.1" 200 248
[10/Jun/2017 06:02:14] "POST /accept/ HTTP/1.1" 200 9
[10/Jun/2017 06:02:24] "GET /static/enroll/acm_a.png HTTP/1.1" 200 10698
[10/Jun/2017 06:02:28] "GET /?nsukey=3LgJcebRYd2owBvw%2FbCAMq6Muy7aS1atbAZfshrPkxjHHhuDBQci7fdTF8Ze4McfEsx2hzYsSaq0cE%2FtuTG8EPj5MJV0uDp4m6sssCX1XU1SzIrOKdxBzSYfIMWaE4GLzGZ11mxnT38E%2FpaxNehJQCTLxC63oo8YzkFc2i2DQ84y9FX3NcWJQrqnGX8SARQB HTTP/1.1" 200 1220
[10/Jun/2017 06:02:28] "GET /?nsukey=3LgJcebRYd2owBvw%2FbCAMq6Muy7aS1atbAZfshrPkxjHHhuDBQci7fdTF8Ze4McfEsx2hzYsSaq0cE%2FtuTG8EPj5MJV0uDp4m6sssCX1XU1SzIrOKdxBzSYfIMWaE4GLzGZ11mxnT38E%2FpaxNehJQCTLxC63oo8YzkFc2i2DQ84y9FX3NcWJQrqnGX8SARQB HTTP/1.1" 200 1220
[10/Jun/2017 06:02:29] "GET /static/enroll/culture.css HTTP/1.1" 200 248
[10/Jun/2017 06:02:30] "GET /?nsukey=3LgJcebRYd2owBvw%2FbCAMq6Muy7aS1atbAZfshrPkxjHHhuDBQci7fdTF8Ze4McfEsx2hzYsSaq0cE%2FtuTG8EPj5MJV0uDp4m6sssCX1XU1SzIrOKdxBzSYfIMWaE4GLzGZ11mxnT38E%2FpaxNehJQCTLxC63oo8YzkFc2i2DQ84y9FX3NcWJQrqnGX8SARQB HTTP/1.1" 200 1220
[10/Jun/2017 06:02:30] "GET /static/enroll/culture.css HTTP/1.1" 200 248
[10/Jun/2017 06:02:30] "GET /static/enroll/acm_a.png HTTP/1.1" 200 10698
[10/Jun/2017 06:02:30] "GET /static/enroll/acm_b.png HTTP/1.1" 200 8077
[10/Jun/2017 06:02:30] "GET /static/enroll/acm_c.png HTTP/1.1" 200 7477
Not Found: /favicon.ico
[10/Jun/2017 06:02:30] "GET /favicon.ico HTTP/1.1" 404 2327
Not Found: /favicon.ico
[10/Jun/2017 06:02:30] "GET /favicon.ico HTTP/1.1" 404 2327
[10/Jun/2017 06:02:34] "GET /?nsukey=3LgJcebRYd2owBvw%2FbCAMq6Muy7aS1atbAZfshrPkxjHHhuDBQci7fdTF8Ze4McfEsx2hzYsSaq0cE%2FtuTG8EPj5MJV0uDp4m6sssCX1XU1SzIrOKdxBzSYfIMWaE4GLzGZ11mxnT38E%2FpaxNehJQCTLxC63oo8YzkFc2i2DQ84y9FX3NcWJQrqnGX8SARQB HTTP/1.1" 200 1220
[10/Jun/2017 06:02:34] "GET /static/enroll/culture.css HTTP/1.1" 200 248
[10/Jun/2017 06:02:34] "GET /static/enroll/acm_a.png HTTP/1.1" 200 10698
[10/Jun/2017 06:02:34] "GET /static/enroll/acm_b.png HTTP/1.1" 200 8077
[10/Jun/2017 06:02:34] "GET /static/enroll/acm_c.png HTTP/1.1" 200 7477
Not Found: /favicon.ico
[10/Jun/2017 06:02:34] "GET /favicon.ico HTTP/1.1" 404 2327
Internal Server Error: /accept/
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/utils/datastructures.py", line 83, in __getitem__
    list_ = super(MultiValueDict, self).__getitem__(key)
KeyError: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/shuacm_enroll/enroll/views.py", line 9, in accept
    if len(request.POST['name'])== 0 or len(request.POST['name']) > 10:
  File "/usr/local/lib/python3.5/dist-packages/django/utils/datastructures.py", line 85, in __getitem__
    raise MultiValueDictKeyError(repr(key))
django.utils.datastructures.MultiValueDictKeyError: "'name'"
[10/Jun/2017 06:02:38] "GET /accept/ HTTP/1.1" 500 69646
Traceback (most recent call last):
  File "/usr/lib/python3.5/wsgiref/handlers.py", line 138, in run
    self.finish_response()
  File "/usr/lib/python3.5/wsgiref/handlers.py", line 180, in finish_response
    self.write(data)
  File "/usr/lib/python3.5/wsgiref/handlers.py", line 279, in write
    self._write(data)
  File "/usr/lib/python3.5/wsgiref/handlers.py", line 463, in _write
    result = self.stdout.write(data)
  File "/usr/lib/python3.5/socket.py", line 593, in write
    return self._sock.send(b)
ConnectionResetError: [Errno 104] Connection reset by peer
[10/Jun/2017 06:02:38] "GET /accept/ HTTP/1.1" 500 59
Traceback (most recent call last):
  File "/usr/lib/python3.5/wsgiref/handlers.py", line 138, in run
    self.finish_response()
  File "/usr/lib/python3.5/wsgiref/handlers.py", line 180, in finish_response
    self.write(data)
  File "/usr/lib/python3.5/wsgiref/handlers.py", line 279, in write
    self._write(data)
  File "/usr/lib/python3.5/wsgiref/handlers.py", line 463, in _write
    result = self.stdout.write(data)
  File "/usr/lib/python3.5/socket.py", line 593, in write
    return self._sock.send(b)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/wsgiref/handlers.py", line 141, in run
    self.handle_error()
  File "/usr/local/lib/python3.5/dist-packages/django/core/servers/basehttp.py", line 88, in handle_error
    super(ServerHandler, self).handle_error()
  File "/usr/lib/python3.5/wsgiref/handlers.py", line 368, in handle_error
    self.finish_response()
  File "/usr/lib/python3.5/wsgiref/handlers.py", line 180, in finish_response
    self.write(data)
  File "/usr/lib/python3.5/wsgiref/handlers.py", line 274, in write
    self.send_headers()
  File "/usr/lib/python3.5/wsgiref/handlers.py", line 331, in send_headers
    if not self.origin_server or self.client_is_modern():
  File "/usr/lib/python3.5/wsgiref/handlers.py", line 344, in client_is_modern
    return self.environ['SERVER_PROTOCOL'].upper() != 'HTTP/0.9'
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 625, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/dist-packages/django/core/servers/basehttp.py", line 155, in handle
    handler.run(self.server.get_app())
  File "/usr/lib/python3.5/wsgiref/handlers.py", line 144, in run
    self.close()
  File "/usr/lib/python3.5/wsgiref/simple_server.py", line 36, in close
    self.status.split(' ',1)[0], self.bytes_sent
AttributeError: 'NoneType' object has no attribute 'split'
[10/Jun/2017 06:03:04] "GET / HTTP/1.1" 200 1220
[10/Jun/2017 06:03:04] "GET /static/enroll/culture.css HTTP/1.1" 200 248
[10/Jun/2017 06:03:04] "GET /static/enroll/acm_a.png HTTP/1.1" 200 10698
[10/Jun/2017 06:03:04] "GET /static/enroll/acm_b.png HTTP/1.1" 200 8077
[10/Jun/2017 06:03:04] "GET /static/enroll/acm_c.png HTTP/1.1" 200 7477
Not Found: /favicon.ico
[10/Jun/2017 06:03:04] "GET /favicon.ico HTTP/1.1" 404 2327
[10/Jun/2017 06:03:40] "GET / HTTP/1.1" 200 1220
[10/Jun/2017 06:03:40] "GET /static/enroll/culture.css HTTP/1.1" 304 0
[10/Jun/2017 06:03:40] "GET /static/enroll/acm_a.png HTTP/1.1" 304 0
[10/Jun/2017 06:03:40] "GET /static/enroll/acm_b.png HTTP/1.1" 304 0
[10/Jun/2017 06:03:40] "GET /static/enroll/acm_c.png HTTP/1.1" 304 0
[10/Jun/2017 06:03:45] "GET / HTTP/1.1" 200 1220
[10/Jun/2017 06:03:46] "GET /static/enroll/culture.css HTTP/1.1" 200 248
[10/Jun/2017 06:03:46] "GET /static/enroll/acm_a.png HTTP/1.1" 200 10698
[10/Jun/2017 06:03:46] "GET /static/enroll/acm_b.png HTTP/1.1" 200 8077
[10/Jun/2017 06:03:46] "GET /static/enroll/acm_c.png HTTP/1.1" 200 7477
[10/Jun/2017 06:03:47] "POST /accept/ HTTP/1.1" 200 9
[10/Jun/2017 06:04:01] "GET / HTTP/1.1" 200 1220
[10/Jun/2017 06:04:01] "GET /static/enroll/culture.css HTTP/1.1" 200 248
[10/Jun/2017 06:04:01] "GET /static/enroll/acm_a.png HTTP/1.1" 200 10698
[10/Jun/2017 06:04:01] "GET /static/enroll/acm_b.png HTTP/1.1" 200 8077
[10/Jun/2017 06:04:01] "GET /static/enroll/acm_c.png HTTP/1.1" 200 7477
[10/Jun/2017 06:04:04] "GET / HTTP/1.1" 200 1220
[10/Jun/2017 06:04:04] "GET /static/enroll/culture.css HTTP/1.1" 304 0
[10/Jun/2017 06:04:04] "GET /static/enroll/acm_a.png HTTP/1.1" 304 0
[10/Jun/2017 06:04:04] "GET /static/enroll/acm_b.png HTTP/1.1" 304 0
[10/Jun/2017 06:04:04] "GET /static/enroll/acm_c.png HTTP/1.1" 304 0
[10/Jun/2017 06:04:05] "GET / HTTP/1.1" 200 1220
[10/Jun/2017 06:04:06] "GET / HTTP/1.1" 200 1220
[10/Jun/2017 06:04:27] "GET / HTTP/1.1" 200 1220
[10/Jun/2017 06:04:27] "GET /static/enroll/culture.css HTTP/1.1" 200 248
[10/Jun/2017 06:04:27] "GET /static/enroll/acm_a.png HTTP/1.1" 200 10698
[10/Jun/2017 06:04:27] "GET /static/enroll/acm_b.png HTTP/1.1" 200 8077
[10/Jun/2017 06:04:27] "GET /static/enroll/acm_c.png HTTP/1.1" 200 7477
[10/Jun/2017 06:04:45] "POST /accept/ HTTP/1.1" 200 9
[10/Jun/2017 06:04:59] "GET / HTTP/1.1" 200 1220
[10/Jun/2017 06:04:59] "GET /static/enroll/culture.css HTTP/1.1" 200 248
[10/Jun/2017 06:04:59] "GET /static/enroll/acm_a.png HTTP/1.1" 200 10698
[10/Jun/2017 06:04:59] "GET /static/enroll/acm_b.png HTTP/1.1" 200 8077
[10/Jun/2017 06:04:59] "GET /static/enroll/acm_c.png HTTP/1.1" 200 7477
[10/Jun/2017 06:05:05] "GET / HTTP/1.1" 200 1220
[10/Jun/2017 06:05:06] "GET /static/enroll/acm_a.png HTTP/1.1" 200 10698
[10/Jun/2017 06:05:06] "GET /static/enroll/culture.css HTTP/1.1" 200 248
[10/Jun/2017 06:05:06] "GET /static/enroll/acm_b.png HTTP/1.1" 200 8077
[10/Jun/2017 06:05:06] "GET /static/enroll/acm_c.png HTTP/1.1" 200 7477
Forbidden (CSRF token missing or incorrect.): /accept/
[10/Jun/2017 06:05:13] "POST /accept/ HTTP/1.1" 403 2502
[10/Jun/2017 06:05:25] "POST /accept/ HTTP/1.1" 200 9
[10/Jun/2017 06:05:43] "GET / HTTP/1.1" 200 1220
[10/Jun/2017 06:05:51] "GET / HTTP/1.1" 200 1220
[10/Jun/2017 06:05:51] "GET /static/enroll/culture.css HTTP/1.1" 304 0
[10/Jun/2017 06:05:51] "GET /static/enroll/acm_a.png HTTP/1.1" 304 0
[10/Jun/2017 06:05:51] "GET /static/enroll/acm_b.png HTTP/1.1" 304 0
[10/Jun/2017 06:05:51] "GET /static/enroll/acm_c.png HTTP/1.1" 304 0
[10/Jun/2017 06:05:56] "GET / HTTP/1.1" 200 1220
[10/Jun/2017 06:06:05] "GET / HTTP/1.1" 200 1220
[10/Jun/2017 06:06:25] "POST /accept/ HTTP/1.1" 200 9
[10/Jun/2017 06:07:07] "GET / HTTP/1.1" 200 1220
[10/Jun/2017 06:07:07] "GET /static/enroll/culture.css HTTP/1.1" 200 248
[10/Jun/2017 06:07:07] "GET /static/enroll/acm_a.png HTTP/1.1" 200 10698
[10/Jun/2017 06:07:07] "GET /static/enroll/acm_b.png HTTP/1.1" 200 8077
[10/Jun/2017 06:07:07] "GET /static/enroll/acm_c.png HTTP/1.1" 200 7477
[10/Jun/2017 06:07:33] "GET / HTTP/1.1" 200 1220
[10/Jun/2017 06:07:34] "GET /static/enroll/culture.css HTTP/1.1" 200 248
[10/Jun/2017 06:07:34] "GET /static/enroll/acm_a.png HTTP/1.1" 200 10698
[10/Jun/2017 06:07:34] "GET /static/enroll/acm_b.png HTTP/1.1" 200 8077
[10/Jun/2017 06:07:34] "GET /static/enroll/acm_c.png HTTP/1.1" 200 7477
[10/Jun/2017 06:08:16] "GET / HTTP/1.1" 200 1220
[10/Jun/2017 06:08:17] "GET /static/enroll/culture.css HTTP/1.1" 304 0
[10/Jun/2017 06:08:17] "GET /static/enroll/acm_a.png HTTP/1.1" 304 0
[10/Jun/2017 06:08:17] "GET /static/enroll/acm_c.png HTTP/1.1" 304 0
[10/Jun/2017 06:08:17] "GET /static/enroll/acm_b.png HTTP/1.1" 304 0
[10/Jun/2017 06:08:53] "POST /accept/ HTTP/1.1" 200 9
Invalid HTTP_HOST header: '123.207.218.48'. You may need to add '123.207.218.48' to ALLOWED_HOSTS.
[10/Jun/2017 06:08:59] "GET / HTTP/1.1" 400 59551
[10/Jun/2017 06:08:59] "GET / HTTP/1.1" 200 1220
[10/Jun/2017 06:09:00] "GET /static/enroll/culture.css HTTP/1.1" 200 248
[10/Jun/2017 06:09:00] "GET /static/enroll/acm_a.png HTTP/1.1" 200 10698
[10/Jun/2017 06:09:00] "GET /static/enroll/acm_b.png HTTP/1.1" 200 8077
[10/Jun/2017 06:09:00] "GET /static/enroll/acm_c.png HTTP/1.1" 200 7477
Invalid HTTP_HOST header: '123.207.218.48'. You may need to add '123.207.218.48' to ALLOWED_HOSTS.
[10/Jun/2017 06:09:00] "GET /favicon.ico HTTP/1.1" 400 59628
Not Found: /favicon.ico
[10/Jun/2017 06:09:00] "GET /favicon.ico HTTP/1.1" 404 2327
[10/Jun/2017 06:09:14] "GET / HTTP/1.1" 200 1220
[10/Jun/2017 06:09:14] "GET /static/enroll/culture.css HTTP/1.1" 200 248
[10/Jun/2017 06:09:14] "GET /static/enroll/acm_b.png HTTP/1.1" 200 8077
[10/Jun/2017 06:09:14] "GET /static/enroll/acm_a.png HTTP/1.1" 200 10698
[10/Jun/2017 06:09:14] "GET /static/enroll/acm_c.png HTTP/1.1" 200 7477
Invalid HTTP_HOST header: '123.207.218.48'. You may need to add '123.207.218.48' to ALLOWED_HOSTS.
[10/Jun/2017 06:09:25] "GET / HTTP/1.1" 400 59682
Invalid HTTP_HOST header: '123.207.218.48'. You may need to add '123.207.218.48' to ALLOWED_HOSTS.
[10/Jun/2017 06:09:26] "GET /favicon.ico HTTP/1.1" 400 59625
[10/Jun/2017 06:09:31] "GET / HTTP/1.1" 200 1220
[10/Jun/2017 06:09:31] "GET /static/enroll/acm_a.png HTTP/1.1" 200 10698
[10/Jun/2017 06:09:31] "GET /static/enroll/culture.css HTTP/1.1" 200 248
[10/Jun/2017 06:09:31] "GET /static/enroll/acm_b.png HTTP/1.1" 200 8077
[10/Jun/2017 06:09:31] "GET /static/enroll/acm_c.png HTTP/1.1" 200 7477
[10/Jun/2017 06:09:38] "GET / HTTP/1.1" 200 1220
[10/Jun/2017 06:09:41] "GET / HTTP/1.1" 200 1220
[10/Jun/2017 06:09:41] "GET /static/enroll/culture.css HTTP/1.1" 200 248
[10/Jun/2017 06:09:41] "GET /static/enroll/acm_a.png HTTP/1.1" 200 10698
[10/Jun/2017 06:09:41] "GET /static/enroll/acm_b.png HTTP/1.1" 200 8077
[10/Jun/2017 06:09:41] "GET /static/enroll/acm_c.png HTTP/1.1" 200 7477
[10/Jun/2017 06:09:41] "GET / HTTP/1.1" 200 1220
[10/Jun/2017 06:10:47] "GET / HTTP/1.1" 200 1220
[10/Jun/2017 06:10:48] "GET /static/enroll/culture.css HTTP/1.1" 200 248
[10/Jun/2017 06:10:48] "GET /static/enroll/acm_a.png HTTP/1.1" 200 10698
[10/Jun/2017 06:10:48] "GET /static/enroll/acm_b.png HTTP/1.1" 200 8077
[10/Jun/2017 06:10:48] "GET /static/enroll/acm_c.png HTTP/1.1" 200 7477
Invalid HTTP_HOST header: '123.207.218.48'. You may need to add '123.207.218.48' to ALLOWED_HOSTS.
[10/Jun/2017 06:11:21] "GET / HTTP/1.1" 400 59683
Invalid HTTP_HOST header: '123.207.218.48'. You may need to add '123.207.218.48' to ALLOWED_HOSTS.
[10/Jun/2017 06:11:22] "GET /favicon.ico HTTP/1.1" 400 59626
[10/Jun/2017 06:11:35] "GET / HTTP/1.1" 200 1220
[10/Jun/2017 06:11:35] "GET /static/enroll/culture.css HTTP/1.1" 200 248
[10/Jun/2017 06:11:35] "GET /static/enroll/acm_a.png HTTP/1.1" 200 10698
[10/Jun/2017 06:11:35] "GET /static/enroll/acm_b.png HTTP/1.1" 200 8077
[10/Jun/2017 06:11:35] "GET /static/enroll/acm_c.png HTTP/1.1" 200 7477
[10/Jun/2017 06:11:57] "GET / HTTP/1.1" 200 1220
[10/Jun/2017 06:11:57] "GET /static/enroll/acm_a.png HTTP/1.1" 200 10698
[10/Jun/2017 06:11:57] "GET /static/enroll/culture.css HTTP/1.1" 200 248
[10/Jun/2017 06:11:57] "GET /static/enroll/acm_b.png HTTP/1.1" 200 8077
[10/Jun/2017 06:11:57] "GET /static/enroll/acm_c.png HTTP/1.1" 200 7477
[10/Jun/2017 06:12:04] "GET / HTTP/1.1" 200 1220
[10/Jun/2017 06:12:04] "GET /static/enroll/acm_a.png HTTP/1.1" 304 0
[10/Jun/2017 06:12:04] "GET /static/enroll/culture.css HTTP/1.1" 304 0
[10/Jun/2017 06:12:04] "GET /static/enroll/acm_b.png HTTP/1.1" 304 0
[10/Jun/2017 06:12:04] "GET /static/enroll/acm_c.png HTTP/1.1" 304 0
[10/Jun/2017 06:12:05] "GET / HTTP/1.1" 200 1220
[10/Jun/2017 06:12:05] "GET /static/enroll/culture.css HTTP/1.1" 200 248
[10/Jun/2017 06:12:05] "GET /static/enroll/acm_a.png HTTP/1.1" 200 10698
[10/Jun/2017 06:12:05] "GET /static/enroll/acm_b.png HTTP/1.1" 200 8077
[10/Jun/2017 06:12:05] "GET /static/enroll/acm_c.png HTTP/1.1" 200 7477
[10/Jun/2017 06:12:25] "GET / HTTP/1.1" 200 1220
[10/Jun/2017 06:12:25] "GET /static/enroll/acm_a.png HTTP/1.1" 304 0
[10/Jun/2017 06:12:25] "GET /static/enroll/culture.css HTTP/1.1" 304 0
[10/Jun/2017 06:12:25] "GET /static/enroll/acm_c.png HTTP/1.1" 304 0
[10/Jun/2017 06:12:25] "GET /static/enroll/acm_b.png HTTP/1.1" 304 0
Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 625, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/dist-packages/django/core/servers/basehttp.py", line 140, in handle
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 625, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/dist-packages/django/core/servers/basehttp.py", line 140, in handle
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 625, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/dist-packages/django/core/servers/basehttp.py", line 140, in handle
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 625, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/dist-packages/django/core/servers/basehttp.py", line 140, in handle
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 625, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/dist-packages/django/core/servers/basehttp.py", line 140, in handle
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 625, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/dist-packages/django/core/servers/basehttp.py", line 140, in handle
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 625, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/dist-packages/django/core/servers/basehttp.py", line 140, in handle
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 625, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/dist-packages/django/core/servers/basehttp.py", line 140, in handle
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 625, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/dist-packages/django/core/servers/basehttp.py", line 140, in handle
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 625, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/dist-packages/django/core/servers/basehttp.py", line 140, in handle
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 625, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/dist-packages/django/core/servers/basehttp.py", line 140, in handle
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 625, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/dist-packages/django/core/servers/basehttp.py", line 140, in handle
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 625, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/dist-packages/django/core/servers/basehttp.py", line 140, in handle
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 625, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/dist-packages/django/core/servers/basehttp.py", line 140, in handle
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 625, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/dist-packages/django/core/servers/basehttp.py", line 140, in handle
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 625, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/dist-packages/django/core/servers/basehttp.py", line 140, in handle
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 625, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/dist-packages/django/core/servers/basehttp.py", line 140, in handle
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 625, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/dist-packages/django/core/servers/basehttp.py", line 140, in handle
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 625, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/dist-packages/django/core/servers/basehttp.py", line 140, in handle
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 625, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/dist-packages/django/core/servers/basehttp.py", line 140, in handle
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 625, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/dist-packages/django/core/servers/basehttp.py", line 140, in handle
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 625, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/dist-packages/django/core/servers/basehttp.py", line 140, in handle
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 625, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/dist-packages/django/core/servers/basehttp.py", line 140, in handle
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 625, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/dist-packages/django/core/servers/basehttp.py", line 140, in handle
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 625, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/dist-packages/django/core/servers/basehttp.py", line 140, in handle
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 625, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/dist-packages/django/core/servers/basehttp.py", line 140, in handle
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 625, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/dist-packages/django/core/servers/basehttp.py", line 140, in handle
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 625, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/dist-packages/django/core/servers/basehttp.py", line 140, in handle
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 625, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/dist-packages/django/core/servers/basehttp.py", line 140, in handle
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 625, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/dist-packages/django/core/servers/basehttp.py", line 140, in handle
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 625, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/dist-packages/django/core/servers/basehttp.py", line 140, in handle
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 625, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/dist-packages/django/core/servers/basehttp.py", line 140, in handle
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 625, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/dist-packages/django/core/servers/basehttp.py", line 140, in handle
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 625, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/dist-packages/django/core/servers/basehttp.py", line 140, in handle
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 625, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/dist-packages/django/core/servers/basehttp.py", line 140, in handle
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 625, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/dist-packages/django/core/servers/basehttp.py", line 140, in handle
    self.raw_requestline = self.rfile.readline(65537)
Performing system checks...

System check identified no issues (0 silenced).
June 10, 2017 - 05:51:19
Django version 1.11.2, using settings 'shuacm.settings'
Starting development server at http://0.0.0.0:80/
Quit the server with CONTROL-C.
----------------------------------------
Exception happened during processing of request from ('103.27.124.226', 53482)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('103.27.124.226', 53484)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('103.27.124.226', 53486)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('103.27.124.226', 53488)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('103.27.124.226', 53490)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('220.181.132.220', 56205)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('211.161.240.33', 45642)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('211.161.240.33', 45643)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('211.161.240.33', 45644)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('49.52.96.148', 57044)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('49.52.96.148', 57045)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('49.52.96.148', 57049)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('211.161.240.33', 45646)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('49.52.96.148', 57055)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('211.103.82.137', 55261)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('49.52.96.148', 57066)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('114.92.142.197', 53198)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('114.92.142.197', 53199)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('114.92.142.197', 53200)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('114.92.142.197', 53202)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('114.92.142.197', 53203)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('114.92.142.197', 53204)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('114.92.142.197', 53205)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('114.92.142.197', 53206)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('114.92.142.197', 53207)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('114.92.142.197', 53208)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('114.92.142.197', 53209)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('114.92.142.197', 53210)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('114.92.142.197', 53211)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('114.92.142.197', 53212)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('114.92.142.197', 53213)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('211.161.240.33', 45649)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('114.92.142.197', 53214)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('114.92.142.197', 53215)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('114.92.142.197', 53216)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('49.52.96.148', 57084)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('202.120.121.27', 37204)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('114.92.142.197', 53218)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('114.92.142.197', 53219)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('114.92.142.197', 53220)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('49.52.97.235', 34326)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('49.52.96.148', 57101)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('49.52.97.71', 57614)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('49.52.97.71', 57618)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('223.104.212.93', 3633)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('101.94.164.172', 11075)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('101.94.218.186', 57550)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('49.52.97.233', 47420)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('101.94.216.84', 27824)
----------------------------------------
----------------------------------------
Exception happened during processing of request from  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 625, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/dist-packages/django/core/servers/basehttp.py", line 140, in handle
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 625, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/dist-packages/django/core/servers/basehttp.py", line 140, in handle
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 625, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/dist-packages/django/core/servers/basehttp.py", line 140, in handle
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 625, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/dist-packages/django/core/servers/basehttp.py", line 140, in handle
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 625, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/dist-packages/django/core/servers/basehttp.py", line 140, in handle
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 625, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/dist-packages/django/core/servers/basehttp.py", line 140, in handle
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 625, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/dist-packages/django/core/servers/basehttp.py", line 140, in handle
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 625, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/dist-packages/django/core/servers/basehttp.py", line 140, in handle
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 625, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/dist-packages/django/core/servers/basehttp.py", line 140, in handle
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 625, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/dist-packages/django/core/servers/basehttp.py", line 140, in handle
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 625, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/dist-packages/django/core/servers/basehttp.py", line 140, in handle
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 625, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/dist-packages/django/core/servers/basehttp.py", line 140, in handle
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 625, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/dist-packages/django/core/servers/basehttp.py", line 140, in handle
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 625, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/dist-packages/django/core/servers/basehttp.py", line 140, in handle
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 625, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/dist-packages/django/core/servers/basehttp.py", line 140, in handle
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 625, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/dist-packages/django/core/servers/basehttp.py", line 140, in handle
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 625, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/dist-packages/django/core/servers/basehttp.py", line 140, in handle
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 625, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/dist-packages/django/core/servers/basehttp.py", line 140, in handle
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 625, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/dist-packages/django/core/servers/basehttp.py", line 140, in handle
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 625, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/dist-packages/django/core/servers/basehttp.py", line 140, in handle
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 625, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/dist-packages/django/core/servers/basehttp.py", line 140, in handle
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 625, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/dist-packages/django/core/servers/basehttp.py", line 140, in handle
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 625, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/dist-packages/django/core/servers/basehttp.py", line 140, in handle
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 625, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/dist-packages/django/core/servers/basehttp.py", line 140, in handle
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 625, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/dist-packages/django/core/servers/basehttp.py", line 140, in handle
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 625, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/dist-packages/django/core/servers/basehttp.py", line 140, in handle
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 625, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/dist-packages/django/core/servers/basehttp.py", line 140, in handle
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 625, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/dist-packages/django/core/servers/basehttp.py", line 140, in handle
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 625, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/dist-packages/django/core/servers/basehttp.py", line 140, in handle
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
Invalid HTTP_HOST header: '123.207.218.48'. You may need to add '123.207.218.48' to ALLOWED_HOSTS.
[10/Jun/2017 06:17:04] "GET / HTTP/1.1" 400 59560
Invalid HTTP_HOST header: '123.207.218.48'. You may need to add '123.207.218.48' to ALLOWED_HOSTS.
[10/Jun/2017 06:17:04] "GET /favicon.ico HTTP/1.1" 400 59638
[10/Jun/2017 06:17:05] code 400, message Bad request syntax ('\x16\x03\x01\x02\x00\x01\x00\x01ü\x03\x03\x12fi§\x80\x9f~U´kÝö\x02ÙÅe\x06D\x90C')
[10/Jun/2017 06:17:05] You're accessing the development server over HTTPS, but it only supports HTTP.

Invalid HTTP_HOST header: '123.207.218.48'. You may need to add '123.207.218.48' to ALLOWED_HOSTS.
[10/Jun/2017 06:17:10] "GET / HTTP/1.1" 400 59077
Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 625, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/dist-packages/django/core/servers/basehttp.py", line 140, in handle
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 625, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/dist-packages/django/core/servers/basehttp.py", line 140, in handle
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 625, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/dist-packages/django/core/servers/basehttp.py", line 140, in handle
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 625, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/dist-packages/django/core/servers/basehttp.py", line 140, in handle
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 625, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/dist-packages/django/core/servers/basehttp.py", line 140, in handle
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 625, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/dist-packages/django/core/servers/basehttp.py", line 140, in handle
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 625, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/dist-packages/django/core/servers/basehttp.py", line 140, in handle
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 625, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/dist-packages/django/core/servers/basehttp.py", line 140, in handle
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 625, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/dist-packages/django/core/servers/basehttp.py", line 140, in handle
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 625, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/dist-packages/django/core/servers/basehttp.py", line 140, in handle
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 625, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/dist-packages/django/core/servers/basehttp.py", line 140, in handle
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 625, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/dist-packages/django/core/servers/basehttp.py", line 140, in handle
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 625, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/dist-packages/django/core/servers/basehttp.py", line 140, in handle
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 625, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/dist-packages/django/core/servers/basehttp.py", line 140, in handle
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
Invalid HTTP_HOST header: '123.207.218.48'. You may need to add '123.207.218.48' to ALLOWED_HOSTS.
[10/Jun/2017 06:17:46] "GET / HTTP/1.1" 400 59077
Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 625, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/dist-packages/django/core/servers/basehttp.py", line 140, in handle
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 625, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/dist-packages/django/core/servers/basehttp.py", line 140, in handle
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 625, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/dist-packages/django/core/servers/basehttp.py", line 140, in handle
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 625, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/dist-packages/django/core/servers/basehttp.py", line 140, in handle
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 625, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/dist-packages/django/core/servers/basehttp.py", line 140, in handle
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
Invalid HTTP_HOST header: '123.207.218.48'. You may need to add '123.207.218.48' to ALLOWED_HOSTS.
[10/Jun/2017 06:18:04] "GET / HTTP/1.1" 400 59077
Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 625, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/dist-packages/django/core/servers/basehttp.py", line 140, in handle
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 625, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/usr/local/lib/python3.5/dist-packages/django/core/servers/basehttp.py", line 140, in handle
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
Invalid HTTP_HOST header: '123.207.218.48'. You may need to add '123.207.218.48' to ALLOWED_HOSTS.
[10/Jun/2017 06:18:53] "GET / HTTP/1.1" 400 59548
Invalid HTTP_HOST header: '123.207.218.48'. You may need to add '123.207.218.48' to ALLOWED_HOSTS.
[10/Jun/2017 06:18:55] "GET /favicon.ico HTTP/1.1" 400 59626
